### ISSUE TITLE
Update object handling to java json

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/BaseAPI#5]
- [x] gigaclub/Base-Plugin#17
- [x] gigaclub/TranslationAPI#12
- [x] gigaclub/Translation-Plugin#6
- [x] gigaclub/BuilderSystemAPI#24
- [x] gigaclub/Builder-System-Plugin#7
